### PR TITLE
TOS-48054: Jenkins-CI-Plugin: Allow to specify only test events instead of the config file

### PR DESCRIPTION
**Pull request by AgileAOTeam**

### CODE REVIEW

**Comment by AgileAOTeam** [comment]
Accept pull request.

**Comment by FrederikCampagne** [comment]
Can this also be published?! Right now I've actually created a solution with TCShell just to do exactly this! Thanks a million! At least jenkins is still picking up the 1.2 and on mvn repo it is indeed still the 1.2.

**Comment by AgileAOTeam** [comment]
@FrederikCampagne We are currently finalizing and finishing testing it. Once we are done we will publish it asap.

**Comment by FrederikCampagne** [comment]
Alright. Thanks for the reply!

**Pull request merged**
